### PR TITLE
Allow docopt-ng 0.8

### PR DESCRIPTION
**Pull request by fgaz**
We're trying to update docopt-ng in nixpkgs: https://github.com/NixOS/nixpkgs/pull/175687

### CODE REVIEW

**Comment by NickCrews** [comment]
@fgaz Hey there! Thanks for this. So I like the change to the docopt-ng version requirement, it makes it less strict, but still keeps us safe from breaking changes if the new minor version has a breaking change.

But, I think the python requirement is good the way it is. If someone wants to use python 3.10 or in the future 3.12, they should be able to, since it shouldn't be backwards incompatible. I don't want to have to update this requirement every time there's a new stable python release.

So the docopt-ng change is good, but can you revert the python dep change? Thanks! I can merge and make a release as soon as you do that.

**Comment by NickCrews** [comment]
Not sure why that python 3.8 windows CI run failed, the python 3.9 windows CI run got past the "install tomlkit" phase. Guessing a flake? We can see if it repeats once you do the suggestions above

**Comment by fgaz** [comment]
> So the docopt-ng change is good, but can you revert the python dep change? Thanks! I can merge and make a release as soon as you do that.
> EDIT:
> I added a fixup commit for you. Once you confirm this looks OK I can merge and release

Yeah the python change was in error, semver rules around 0.x versions got me confused... Thanks for fixing it!

**Comment by NickCrews** [comment]
Fixed in https://github.com/staticjinja/staticjinja/pull/171

**Pull request closed without merging**
