### PR TITLE
Fix and unify version numbers, update and fix setup.py, __init__.py, README

### PR DESCRIPTION
**Pull request by NickCrews**
The version number was out of sync between setup.py, what you saw from cli.py when running `staticjinja --version`, and what sphinx built for the docs. In addition, the actual package didn't have a __version__ attribute! So you couldn't do `import staticjinja; staticjinja.__version__`

There were many possible ways to unify the version, I followed https://packaging.python.org/guides/single-sourcing-package-version/ for guidance.

This changes the output of running `staticjinja --version` from the form `staticjinja 0.3.0` to just `0.3.0`, which might break someone's something, but I think the old way was incorrect. Just the version number is easier to work with programmtically, and all the examples from the docopt package use this new way.

### CODE REVIEW

**Comment by NickCrews** [comment]
While I'm at it I'm adding some other fixups and small improvements to this PR.

**Comment by NickCrews** [comment]
@PatrickMassot I added you in case you were interested, but feel no pressure to review/help if you don't want.

**Comment by NickCrews** [comment]
Alright, after a bunch of tries to get the linter to pass, it looks like we're good now.

**Comment by PatrickMassot** [comment]
It looks good to me. Why not adding python 3.9 in setup.py? Is there any issue with this version?

**Comment by NickCrews** [comment]
Thanks Patrick! I don't think 3.9 is tested by Travis CI so I didn't want
to explicitly say it's supported, but it probably works just fine. I can
probably add it though to Travis, if so then I'll add it here as well.

**Pull request merged**
